export const ROLES = {
  GN_OFFICER: 'GN_OFFICER',
  DONOR: 'DONOR',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const PRIORITY_LEVELS = {
  CRITICAL: 'CRITICAL',
  MODERATE: 'MODERATE',
  LOW: 'LOW',
};

export const SUPPLY_CATEGORIES = {
  MEDICAL: 'MEDICAL',
  FOOD: 'FOOD',
  UTILITY: 'UTILITY',
  SHELTER: 'SHELTER',
  COMMUNICATION: 'COMMUNICATION',
};

export const STATUS_TYPES = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  DELIVERED: 'DELIVERED',
};
